<?php

namespace App\Models;

use App\Models\Scopes\ClientScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @property  int $client_status
 * @property  string $password
 */
class Client extends User
{
    use HasFactory;

    protected $table = "users";
    protected $guarded = ["id"];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ClientScope);
    }

    public function getStatus(): string
    {
        return match ($this->client_status) {
            0 => "Đang hợp tác",
            1 => "Hợp tác ít",
            2 => "Ngừng hợp tác",
            default => "Không xác định",
        };
    }
}
