<?php

namespace App\Models;

use App\Models\Scopes\PartnerScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @property int $client_status
 * @property string $password
 */
class Partner extends User
{
    use HasFactory;

    protected $table = "users";
    protected $guarded = ['id'];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new PartnerScope);
    }

    public function getStatus(): string
    {
        return match ($this->client_status) {
            "0" => "Đang họp tác",
            "1" => "Hợp tác ít",
            "2" => "Ngừng hợp tác",
            default => "Không xác định",
        };
    }
}
