<?php

namespace App\Models;

use App\Models\Scopes\StaffScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;


class Staff extends User
{
    use HasFactory;

    protected $table = "users";
    protected $guarded = ["id"];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new StaffScope);
    }

    public function Students(): HasMany
    {
        return $this->hasMany(Student::class, "staff_id", "id");
    }

    public function Grades(): BelongsToMany
    {
        return $this->belongsToMany(Grade::class, "staff_grade", "staff_id", "grade_id");
    }
}
