<?php

namespace App\Models;

use App\Models\Scopes\StopGradeScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StopGrade extends Grade
{
    use HasFactory;

    public static function boot(): void
    {
        parent::subBoot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new StopGradeScope);
    }
}
