<?php

namespace App\Repositories;

use App\Models\Grade;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class GradeRepository extends CrudRepository
{

    public function __construct(Grade $grade)
    {
        $this->model = $grade;
    }

    /**
     * @param Builder $query
     * @param array $attributes
     * @return Builder
     */
    public function filter(Builder $query, array $attributes): Builder
    {
        $query->where("status",0);
        if (isset($attributes['name'])) {
            $value = $attributes["name"];
            $query->where("name", "like", "%$value%");
        }
        if (isset($attributes['students'])) {
            $value = $attributes["students"];
            $query->whereHas("students", function (Builder $student) use ($value) {
                $student->where("name", "like", "%$value%");
            });
        }
        if (isset($attributes['teachers'])) {
            $value = $attributes["teachers"];
            $query->whereHas("teachers", function (Builder $teachers) use ($value) {
                $teachers->where("name", "like", "%$value%");
            });
        }
        return parent::filter($query, $attributes); // TODO: Change the autogenerated stub
    }


}
