<?php

namespace App\Repositories;

use App\Models\Log;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;

class LogRepository extends CrudRepository
{
    public function __construct(Log $log)
    {
        $this->model = $log;
    }

    /**
     * @param Builder $query
     * @param array $attributes
     * @return Builder
     */
    public function filter(Builder $query, array $attributes): Builder
    {
        $query->whereHas("grade", function (Builder $builder) {
            $builder->where("disable", 0);
        });
        if (isset($attributes['grade'])) {
            $value = $attributes["grade"];
            $query->whereHas("grade", function (Builder $grade) use ($value) {
                $grade->where("name", "like", "%$value%");
            });
        }
        return parent::filter($query, $attributes); // TODO: Change the autogenerated stub
    }

    public function getLogByGrade($gradeId): Collection|array
    {
        return $this->getQuery()->whereHas("grade", function (Builder $grade)use ($gradeId) {
            $grade->where("id", $gradeId);
        })->orderBy("created_at", "DESC")->get();
    }
}
