<?php

namespace App\Repositories;

use App\Models\Log;
use Illuminate\Database\Eloquent\Builder;

class LogRepository extends CrudRepository
{
    public function __construct(Log $log)
    {
        $this->model = $log;
    }

    /**
     * @param Builder $query
     * @param array $attributes
     * @return Builder
     */
    public function filter(Builder $query, array $attributes): Builder
    {
        if (isset($attributes['grade'])) {
            $value = $attributes["grade"];
            $query->whereHas("grade", function (Builder $grade) use ($value) {
                $grade->where("name", "like", "%$value%");
            });
        }
        return parent::filter($query, $attributes); // TODO: Change the autogenerated stub
    }
}
