<?php

namespace App\Repositories;

use App\Models\Student;
use Illuminate\Database\Eloquent\Builder;

class StudentRepository extends CrudRepository
{

    public function __construct(Student $student)
    {
        $this->model = $student;
    }

    public function filter(Builder $query, array $attributes): Builder
    {
        return parent::filter($query, $attributes); // TODO: Change the autogenerated stub
    }
}
