<?php

namespace App\Repositories;

use App\Models\Student;
use Illuminate\Database\Eloquent\Builder;

class StudentRepository extends CrudRepository
{

    public function __construct(Student $student)
    {
        $this->model = $student;
    }

    public function filter(Builder $query, array $attributes): Builder
    {
        if (principal()->getType() == 0) {
            $query->where(function (Builder $student) {
                $student->where("staff_id", principal()->getId())
                    ->orWhereHas("grades", function (Builder $grades) {
                        $grades->whereHas("staffs", function (Builder $staffs) {
                            $staffs->where("id", principal()->getId());
                        });
                    });
            });
        }
        return parent::filter($query, $attributes); // TODO: Change the autogenerated stub
    }
}
