<?php

namespace App\Repositories;

use App\Models\Teacher;
use Illuminate\Database\Eloquent\Builder;

class TeacherRepository extends CrudRepository
{

    public function __construct(Teacher $teacher)
    {
        $this->model = $teacher;
    }

    public function filter(Builder $query, array $attributes): Builder
    {
        if (principal()->getType() == 0) {
            $query->whereHas("grades", function (Builder $grades) {
                $grades->whereHas("staffs", function (Builder $staffs) {
                    $staffs->where("id", principal()->getId());
                })->orWhereHas("supporters", function (Builder $supporters) {
                    $supporters->where("id", principal()->getId());
                });
            });
        }
        return parent::filter($query, $attributes); // TODO: Change the autogenerated stub
    }
}
